import type { GtinManagementRule } from "./types";

/**
 * Default GTIN Management rules expressed as data so they can be replaced
 * without rewriting application code. Explanations paraphrase operational
 * outcomes; they are not a reproduction of the standard.
 */
export const DEFAULT_GTIN_MANAGEMENT_RULES: GtinManagementRule[] = [
  {
    id: "net-content",
    field: "netContentValue",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "Declared net content has changed. A new GTIN is required for the successor trade item.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "net-content-unit",
    field: "netContentUnit",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "The unit of declared net content has changed.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "pack-quantity",
    field: "packQuantity",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "Pack quantity / number of items in the trade item has changed.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "packaging-level",
    field: "packagingLevel",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "Packaging hierarchy level has changed. Each level needs its own GTIN.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "primary-brand",
    field: "primaryBrand",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "The primary brand appearing to the consumer has changed.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "brand",
    field: "brand",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "Brand identity of the trade item has changed.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "formulation",
    field: "formulationKey",
    comparator: "changed",
    decision: "NEW_GTIN_REQUIRED",
    severity: "BLOCKING",
    explanation: "Formulation or declared functionality has changed in a way that creates a different trade item.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "functionality",
    field: "functionality",
    comparator: "changed",
    decision: "REVIEW_REQUIRED",
    severity: "WARNING",
    explanation: "Functionality description changed. Review whether a new GTIN is required.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "gross-weight",
    field: "grossWeightValue",
    comparator: "changedBeyondPercent",
    thresholdPercent: 20,
    decision: "REVIEW_REQUIRED",
    severity: "WARNING",
    explanation: "Gross weight changed by more than 20%. Review identification impact before publishing.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "length",
    field: "lengthMm",
    comparator: "changedBeyondPercent",
    thresholdPercent: 20,
    decision: "REVIEW_REQUIRED",
    severity: "WARNING",
    explanation: "A declared dimension changed by more than 20%. Review packaging identification.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "regulatory",
    field: "regulatoryDeclaration",
    comparator: "changed",
    decision: "REVIEW_REQUIRED",
    severity: "WARNING",
    explanation: "A regulatory declaration changed. Confirm whether the trade item identity also changed.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
  {
    id: "consumer-name",
    field: "consumerFacingName",
    comparator: "changed",
    decision: "REVIEW_REQUIRED",
    severity: "WARNING",
    explanation: "Consumer-facing product name changed. Review whether shoppers would treat this as a different item.",
    enabled: true,
    standardKey: "GS1_GTIN_MANAGEMENT",
    standardVersion: "2.0.1",
  },
];
