export const languages = [
  { code: "en", name: "English", nativeName: "English", isRecommended: true, isRtl: false },
  { code: "pl", name: "Polish", nativeName: "Polski", isRecommended: false, isRtl: false },
  { code: "fr", name: "French", nativeName: "Français", isRecommended: false, isRtl: false },
  { code: "de", name: "German", nativeName: "Deutsch", isRecommended: false, isRtl: false },
  { code: "es", name: "Spanish", nativeName: "Español", isRecommended: false, isRtl: false },
  { code: "it", name: "Italian", nativeName: "Italiano", isRecommended: false, isRtl: false },
  { code: "ko", name: "Korean", nativeName: "한국어", isRecommended: false, isRtl: false },
  { code: "ja", name: "Japanese", nativeName: "日本語", isRecommended: false, isRtl: false },
  { code: "zh", name: "Chinese", nativeName: "中文", isRecommended: false, isRtl: false },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", isRecommended: false, isRtl: false },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", isRecommended: false, isRtl: false },
  { code: "ar", name: "Arabic", nativeName: "العربية", isRecommended: false, isRtl: true },
  { code: "pt", name: "Portuguese", nativeName: "Português", isRecommended: false, isRtl: false },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", isRecommended: false, isRtl: false },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", isRecommended: false, isRtl: false },
  { code: "ro", name: "Romanian", nativeName: "Română", isRecommended: false, isRtl: false },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", isRecommended: false, isRtl: false },
  { code: "cs", name: "Czech", nativeName: "Čeština", isRecommended: false, isRtl: false },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", isRecommended: false, isRtl: false },
] as const;

export const allergens = [
  { code: "MILK", name: "Milk" },
  { code: "EGGS", name: "Eggs" },
  { code: "FISH", name: "Fish" },
  { code: "SHELLFISH", name: "Shellfish" },
  { code: "TREE_NUTS", name: "Tree nuts" },
  { code: "PEANUTS", name: "Peanuts" },
  { code: "WHEAT", name: "Wheat" },
  { code: "SOY", name: "Soy" },
  { code: "SESAME", name: "Sesame" },
  { code: "CELERY", name: "Celery" },
  { code: "MUSTARD", name: "Mustard" },
  { code: "LUPIN", name: "Lupin" },
  { code: "MOLLUSCS", name: "Molluscs" },
  { code: "SULPHITES", name: "Sulphites" },
] as const;

export const certifications = [
  { slug: "organic", name: "Organic" },
  { slug: "vegan", name: "Vegan" },
  { slug: "vegetarian", name: "Vegetarian" },
  { slug: "halal", name: "Halal" },
  { slug: "kosher", name: "Kosher" },
  { slug: "fairtrade", name: "Fairtrade" },
  { slug: "gluten-free", name: "Gluten Free" },
] as const;

export const categories = [
  {
    slug: "food-beverage",
    name: "Food & Beverage",
    description: "Packaged foods and drinks",
    children: [
      { slug: "dairy", name: "Dairy" },
      { slug: "bakery", name: "Bakery" },
      { slug: "meat-seafood", name: "Meat & Seafood" },
      { slug: "beverages", name: "Beverages" },
      { slug: "snacks", name: "Snacks" },
      { slug: "condiments", name: "Condiments" },
    ],
  },
  {
    slug: "health-beauty",
    name: "Health & Beauty",
    description: "Personal care and health products",
    children: [
      { slug: "skincare", name: "Skincare" },
      { slug: "oral-care", name: "Oral care" },
    ],
  },
  {
    slug: "household",
    name: "Household",
    description: "Home and cleaning products",
    children: [{ slug: "cleaning", name: "Cleaning" }],
  },
  {
    slug: "electronics",
    name: "Electronics",
    description: "Consumer electronics",
    children: [],
  },
  {
    slug: "apparel",
    name: "Apparel",
    description: "Clothing and accessories",
    children: [],
  },
] as const;

export const countries: Array<{ iso2: string; iso3: string; name: string; numeric: string }> = [
  { iso2: "PL", iso3: "POL", name: "Poland", numeric: "616" },
  { iso2: "GB", iso3: "GBR", name: "United Kingdom", numeric: "826" },
  { iso2: "US", iso3: "USA", name: "United States", numeric: "840" },
  { iso2: "DE", iso3: "DEU", name: "Germany", numeric: "276" },
  { iso2: "FR", iso3: "FRA", name: "France", numeric: "250" },
  { iso2: "ES", iso3: "ESP", name: "Spain", numeric: "724" },
  { iso2: "IT", iso3: "ITA", name: "Italy", numeric: "380" },
  { iso2: "NL", iso3: "NLD", name: "Netherlands", numeric: "528" },
  { iso2: "BE", iso3: "BEL", name: "Belgium", numeric: "056" },
  { iso2: "IE", iso3: "IRL", name: "Ireland", numeric: "372" },
  { iso2: "SE", iso3: "SWE", name: "Sweden", numeric: "752" },
  { iso2: "NO", iso3: "NOR", name: "Norway", numeric: "578" },
  { iso2: "DK", iso3: "DNK", name: "Denmark", numeric: "208" },
  { iso2: "FI", iso3: "FIN", name: "Finland", numeric: "246" },
  { iso2: "PT", iso3: "PRT", name: "Portugal", numeric: "620" },
  { iso2: "AT", iso3: "AUT", name: "Austria", numeric: "040" },
  { iso2: "CH", iso3: "CHE", name: "Switzerland", numeric: "756" },
  { iso2: "CZ", iso3: "CZE", name: "Czechia", numeric: "203" },
  { iso2: "SK", iso3: "SVK", name: "Slovakia", numeric: "703" },
  { iso2: "HU", iso3: "HUN", name: "Hungary", numeric: "348" },
  { iso2: "RO", iso3: "ROU", name: "Romania", numeric: "642" },
  { iso2: "BG", iso3: "BGR", name: "Bulgaria", numeric: "100" },
  { iso2: "GR", iso3: "GRC", name: "Greece", numeric: "300" },
  { iso2: "LT", iso3: "LTU", name: "Lithuania", numeric: "440" },
  { iso2: "LV", iso3: "LVA", name: "Latvia", numeric: "428" },
  { iso2: "EE", iso3: "EST", name: "Estonia", numeric: "233" },
  { iso2: "UA", iso3: "UKR", name: "Ukraine", numeric: "804" },
  { iso2: "TR", iso3: "TUR", name: "Türkiye", numeric: "792" },
  { iso2: "CA", iso3: "CAN", name: "Canada", numeric: "124" },
  { iso2: "MX", iso3: "MEX", name: "Mexico", numeric: "484" },
  { iso2: "BR", iso3: "BRA", name: "Brazil", numeric: "076" },
  { iso2: "AR", iso3: "ARG", name: "Argentina", numeric: "032" },
  { iso2: "CL", iso3: "CHL", name: "Chile", numeric: "152" },
  { iso2: "AU", iso3: "AUS", name: "Australia", numeric: "036" },
  { iso2: "NZ", iso3: "NZL", name: "New Zealand", numeric: "554" },
  { iso2: "JP", iso3: "JPN", name: "Japan", numeric: "392" },
  { iso2: "KR", iso3: "KOR", name: "South Korea", numeric: "410" },
  { iso2: "CN", iso3: "CHN", name: "China", numeric: "156" },
  { iso2: "IN", iso3: "IND", name: "India", numeric: "356" },
  { iso2: "ID", iso3: "IDN", name: "Indonesia", numeric: "360" },
  { iso2: "TH", iso3: "THA", name: "Thailand", numeric: "764" },
  { iso2: "VN", iso3: "VNM", name: "Vietnam", numeric: "704" },
  { iso2: "MY", iso3: "MYS", name: "Malaysia", numeric: "458" },
  { iso2: "SG", iso3: "SGP", name: "Singapore", numeric: "702" },
  { iso2: "PH", iso3: "PHL", name: "Philippines", numeric: "608" },
  { iso2: "AE", iso3: "ARE", name: "United Arab Emirates", numeric: "784" },
  { iso2: "SA", iso3: "SAU", name: "Saudi Arabia", numeric: "682" },
  { iso2: "ZA", iso3: "ZAF", name: "South Africa", numeric: "710" },
  { iso2: "EG", iso3: "EGY", name: "Egypt", numeric: "818" },
  { iso2: "NG", iso3: "NGA", name: "Nigeria", numeric: "566" },
  { iso2: "KE", iso3: "KEN", name: "Kenya", numeric: "404" },
  { iso2: "IL", iso3: "ISR", name: "Israel", numeric: "376" },
];
